DetectionTemplates: ["alert_template.yml","alert_template.txt", "documentation_template.md"]
HuntTemplates: []
entry_question.choices: ["DETECTION","HUNT"]
detection_author: ["your.email@exmaple.com"]